package StoreApp;


/**
* StoreApp/StoreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Store.idl/
* Sunday, October 18, 2020 5:48:59 o'clock PM EDT
*/

public interface StoreOperations 
{
  String addItem (String managerID, String itemID, String itemName, int qty, int price);
  String removeItem (String managerID, String itemID, int qty);
  String listItemAvailability (String managerID);
  String purchaseItem (String customerID, String itemID, String dateOfPurchase);
  String returnItem (String customerID, String itemID, String dateOfReturn);
  String findItem (String customerID, String itemName);
  String exchangeLogic (String customerID, String itemID, String oldItemID, String dateOfReturn);
} // interface StoreOperations
