package StoreApp;


/**
* StoreApp/Store.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Store.idl/
* Sunday, October 18, 2020 5:48:59 o'clock PM EDT
*/

public interface Store extends StoreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Store
